# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 10:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20171114_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
