# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_auto_20171114_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
