# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_auto_20171114_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='files',
        ),
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
    ]
