# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 11:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
