# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_auto_20171115_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
