# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 19:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_article_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='files',
        ),
        migrations.AddField(
            model_name='article',
            name='drive_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
