# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-25 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0015_auto_20171121_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
    ]
