# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0016_remove_article_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
